workflows:
  ios-ipa-build:
    name: iOS IPA Build (No Code Signing)
    instance_type: mac_mini
    max_build_duration: 30
    environment:
      vars:
        FLUTTER_VERSION: 3.22.1
      flutter: $FLUTTER_VERSION
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS .app
        script: |
          flutter build ios --release --no-codesign
      - name: Package .ipa from .app
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
    artifacts:
      - Runner.ipa
